### ISSUE TITLE
assertIssuerKeywords

### ISSUE THREAD

**Issue by GrigoriGrigoryanBytepitch** [alexanderem49/simple-exchange#21]
[Agoric storage viewer.pdf](https://github.com/alexanderem49/simple-exchange/files/13225970/Agoric.storage.viewer.pdf)

**Comment by Jorge-Lopes** [comment]
Gist https://gist.github.com/Jorge-Lopes/97e880829e21b46537064855a45da849
patterns: https://github.com/Agoric/agoric-sdk/blob/65d3f14c8102993168d2568eed5e6acbcba0c48a/packages/store/src/types.js#L483
