### ISSUE TITLE
Issue related to 'makeAgoricWalletConnection'

### ISSUE THREAD

**Issue by Jorge-Lopes** [alexanderem49/simple-exchange#29]
## Context

When running the UI, no error is triggered in the console after executing `yarn run dev` but the browser window stays empty with the following error being printed in the browser console:

```
NavBar.jsx:3 Uncaught SyntaxError: The requested module '/@fs/Users/jorgelopes/Documents/GitHub/Agoric/agoric-sdk/packages/web-components/index.js' does not provide an export named 'makeAgoricWalletConnection' (at NavBar.jsx:3:10)
```

On the Agoric client terminal, the following message was logged:
```
outbound: eek, no delivery method for target 5b65c040719bf5385448437e9e65e12c6fc5e3260db12527cd687326156076e8
```

**Comment by Jorge-Lopes** [comment]
Both methods ` { makeAgoricWalletConnection, suggestChain }` imported from `@agoric/web-components` does not exist in the version defined on the package.json `@agoric/web-components": "0.12.1-dev-74299fa.0` 

This is my `web-components/index.js` file:
```
// @ts-check

// Ambient types. https://github.com/Agoric/agoric-sdk/issues/6512
import '@agoric/swingset-vat/src/vats/network/types.js';
import '@agoric/governance/src/types-ambient.js';

export { AgoricWalletConnection } from './src/AgoricWalletConnection.js';
export { makeAgoricKeplrConnection } from './src/keplr-connection/KeplrConnection.js';
export { Errors as AgoricKeplrConnectionErrors } from './src/keplr-connection/errors.js';
export {
  DappWalletBridge,
  BridgeProtocol,
} from './src/dapp-wallet-bridge/DappWalletBridge.js';
```

**Comment by Jorge-Lopes** [comment]
Issue solved with the structure update. **(develop branch)**
Although, when tested, the table was showing dummy data instead of the orders made by the scripts.
The orders were visible in the storageViewer and wallet REPL

@GrigoriGrigoryanBytepitch

**Comment by rabi-siddique** [comment]
> Both methods ` { makeAgoricWalletConnection, suggestChain }` imported from `@agoric/web-components` does not exist in the version defined on the package.json `@agoric/web-components": "0.12.1-dev-74299fa.0`
> 
> This is my `web-components/index.js` file:
> 
> ```
> // @ts-check
> 
> // Ambient types. https://github.com/Agoric/agoric-sdk/issues/6512
> import '@agoric/swingset-vat/src/vats/network/types.js';
> import '@agoric/governance/src/types-ambient.js';
> 
> export { AgoricWalletConnection } from './src/AgoricWalletConnection.js';
> export { makeAgoricKeplrConnection } from './src/keplr-connection/KeplrConnection.js';
> export { Errors as AgoricKeplrConnectionErrors } from './src/keplr-connection/errors.js';
> export {
>   DappWalletBridge,
>   BridgeProtocol,
> } from './src/dapp-wallet-bridge/DappWalletBridge.js';
> ```

@Jorge-Lopes Thanks for documenting this issue. I was facing the same thing today. 
Were you able to overcome this problem?

**Comment by Jorge-Lopes** [comment]
Greetings @rabi-siddique 

I regret not documenting the solution, since now it is difficult to remember in detail.
But if I am not mistaken, the issue was related to conflict between the dependencies defined in the root of the project and the ones defined in the ui directory.

The solution was to remove the package.json from the root and ensure that the version defined in the ui was the correct one.

I hope this is helpful for you

**Comment by rabi-siddique** [comment]
> Greetings @rabi-siddique
> 
> I regret not documenting the solution, since now it is difficult to remember in detail. But if I am not mistaken, the issue was related to conflict between the dependencies defined in the root of the project and the ones defined in the ui directory.
> 
> The solution was to remove the package.json from the root and ensure that the version defined in the ui was the correct one.
> 
> I hope this is helpful for you

Thanks for sharing @Jorge-Lopes :)
