### ISSUE TITLE
Displaying an Agoric Amount Correctly

### ISSUE THREAD

**Issue by anilhelvaci** [alexanderem49/simple-exchange#6]
## Context
The UI component that handles sending offers to the contract must work as a bridge between human readable input values and Agoric amounts. For that [@agoric/ui-kit](https://github.com/Agoric/ui-kit) has two complementary methods that handles this problem:
* [parseAsAmount](https://github.com/Agoric/ui-kit/blob/7c365a1804b95b41dd0fd81cd81dfb3778295b71/packages/ui-components/src/display/display.js#L44)
* [strignifyValue](https://github.com/Agoric/ui-kit/blob/7c365a1804b95b41dd0fd81cd81dfb3778295b71/packages/ui-components/src/display/display.js#L61)

## Problem
These two methods above need the `displayInfo` whichever amount they're displaying/parsing at any point in time. This `displayInfo` has the following properties;
* AssetKind = `nat` or `set`
* decimalPlaces = {number}

We need a dynamic way to keep track of these information in our UI app.

## Solution
`vstorage` has this information in three separate paths;
* boardAux
* vbankAsset
* vbankPurses

For the purposes of this project `vbankAsset` is the easiest place to fetch `displayInfo` when the ease of creating testing environment is considered.

### Storage Watcher
`storageWatcher` works with paths to indicate the location of the required data. For the current problem at hand, here's the path to fetch `vbankAsset` data:

```
published.agoricNames.vbankAsset 
```

Remember that we're interested in the actual data and not child nodes of the path specified. So the method to add in the `storageWatcher.js` would look like this:

```js
const watchVbankAsset = () => {
        watcher.watchLatest(
            [AgoricChainStoragePathKind.Data, 'published.agoricNames.vbankAsset'],
            vbankAssets => {
                console.log('VBankAsset Update', vbankAssets);
                // Call your zustand parser method here
            }
        );
    };
```

### Using `displayInfo` in the store
Now that we've the `displayInfo` in the zustand, it's time to use it in our UI components. here are some key assumptions about consuming `displayInfo` data;
* There's a method called `getDisplayInfo(amount)` that accepts an amount and returns the `displayInfo`

Here's an example method for displaying an agoric amount
```js
const displayAmount = amount => {
    const { brand, value } = amount;
    const { getDisplayInfo } = useStore.getState();
    const displayInfo = getDisplayInfo(brand);

    if (!displayInfo) return '';

    const { assetKind, decimalPlaces } = displayInfo;
    return stringifyValue(value, assetKind, decimalPlaces);
};
```

### Parsing User Input
When the user types a number in the text field, we should call a method similar to the example below in the `onChange`(or whatever is fired on user input)  callback;
```js
const parseUserInput = (brand, ev, setUserInput) => {
  const { getDisplayInfo } = useStore.getState();
  const displayInfo = getDisplayInfo(brand);
  
  if (!displayInfo) return AmountMath.makeEmpty(brand);

  const { assetKind, decimalPlaces } = displayInfo;
  const str = ev.target?.value
                ?.replace('-', '')
                .replace('e', '')
                .replace('E', '');

  const parsed = parseAsAmount(str, brand, assetKind, decimalPlaces);
  setUserInput(parsed);
};
```

**Comment by anilhelvaci** [comment]
## Starting the blockchain
```
git clone https://github.com/Agoric/agoric-sdk.git
cd agoric-sdk/
git checkout agoric-upgrade-11wf
yarn && yarn build
cd packages/inter-protocol
./scripts/start-local-chain.sh
```

**Comment by GrigoriGrigoryanBytepitch** [comment]
@anilhelvaci here is the pull request for this task https://github.com/alexanderem49/simple-exchange/pull/7
